name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/apps/q7o
            
            # Сохраняем текущий .env если есть
            if [ -f .env ]; then
              cp .env .env.backup
            fi
            
            # Обновляем код
            git pull origin main
            
            # Создаем .env из GitHub Secrets
            cat > .env << 'EOL'
            ${{ secrets.ENV_FILE }}
            EOL
            
            # Пересобираем и перезапускаем контейнеры
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            
            # Перезапускаем LiveKit
            docker-compose -f docker-compose.livekit.yml down
            docker-compose -f docker-compose.livekit.yml up -d
            
            # Очистка неиспользуемых Docker образов
            docker image prune -a -f --filter "until=1h"
            
            # Проверяем статус
            docker ps
            
            echo "Deploy completed!"